base:
    seed: &seed 42
model:
    type: Qwen2
    path: /mnt/share/toky/LLMs/Qwen2-0.5B/
    torch_dtype: auto
eval:
    eval_pos: [pretrain, transformed, fake_quant]
    name: wikitext2
    download: False
    path: /mnt/share/toky/Datasets/LLMC/wikitext2/
    seq_len: 2048
    # For 7B / 13B model eval, bs can be set to "1", and inference_per_block can be set to "False".
    # For 70B model eval, bs can be set to "20", and inference_per_block can be set to "True".
    bs: 1
    inference_per_block: False
quant:
    method: Quarot
    weight:
        bit: 8
        symmetric: False
        granularity: per_channel
        group_size: -1
        calib_algo: minmax
    act:
        bit: 8
        symmetric: False
        granularity: per_token
    special:
        rotate_mode: hadamard
        fp32_had: True
        online_rotate: True
save:
    save_trans: False
    save_fake: False
    save_path: /mnt/share/toky/Projects/LLMC_Test/llmc_quantized/Qwen2-0.5B-quarot_w_a
