base:
    seed: &seed 0
model:
    type: SmolLM
    path: /mnt/share/toky/LLMs/SmolLM-135M-Instruct/
    torch_dtype: auto
    modality: language
calib:
    name: wikitext2
    download: False
    path: /mnt/share/toky/Datasets/LLMC/wikitext2/
    n_samples: 1
    bs: 1
    seq_len: 2048
    preproc: wikitext2_gptq
    seed: *seed
eval:
    eval_pos: [pretrain, fake_quant]
    name: wikitext2
    download: False
    path: /mnt/share/toky/Datasets/LLMC/wikitext2/
    seq_len: 2048
    # For 7B / 13B model eval, bs can be set to "1", and inference_per_block can be set to "False".
    # For 70B model eval, bs can be set to "20", and inference_per_block can be set to "True".
    bs: 1
    inference_per_block: False
quant:
    method: DGQ
    true_sequential: False
    mixed_precision: True
    weight:
        w_1:
            bit: 4
            symmetric: False
            granularity: per_group
            group_size: 16
        w_2:
            bit: 8
            symmetric: True
            granularity: per_channel
    act:
        bit: 8
        symmetric: True
        granularity: per_token
        static: False  # 新增：是否使用静态激活量化
        mix_bits: False  # 新增

save:
    save_trans: False
    save_fake: False
    save_path: /mnt/share/toky/Projects/LLMC_Test/llmc_quantized/SmolLM-135M-Instruct-dgq_w_a
