base:
    seed: &seed 42
model:
    type: Qwen2
    path: /mnt/share/toky/LLMs/Qwen2-0.5B/
    torch_dtype: auto
calib:
    name: pileval
    download: False
    path: /mnt/share/toky/Datasets/LLMC/pileval/
    n_samples: 128
    bs: 1
    seq_len: 512
    preproc: txt_general_preproc
    seed: *seed
eval:
    eval_pos: [pretrain, fake_quant]
    name: wikitext2
    download: False
    path: /mnt/share/toky/Datasets/LLMC/wikitext2/
    seq_len: 2048
    # For 7B / 13B model eval, bs can be set to "1", and inference_per_block can be set to "False".
    # For 70B model eval, bs can be set to "20", and inference_per_block can be set to "True".
    bs: 1
    inference_per_block: False
quant:
    method: NormTweaking
    weight:
        bit: 8
        symmetric: True
        granularity: per_channel
        group_size: -1
    act:
        bit: 8
        symmetric: True
        granularity: per_token
    special:
        ntweak_lr: 0.000001
        deactive_amp: True
        epochs: 50
        gamma: 0.001
    quant_out: True
save:
    save_fake: False
    save_path: /mnt/share/toky/Projects/LLMC_Test/llmc_quantized/Qwen2-0.5B-Instruct-ntweak_w_a
