base:
    seed: &seed 42
model:
    type: Qwen2
    path: /mnt/share/toky/LLMs/Qwen2-0.5B/
    torch_dtype: auto
eval:
    eval_pos: [transformed, fake_quant, fake_quant_wo_kv] #decode_ppl eval not support pretrain eval pos
    name: wikitext2
    type: decode_ppl
    download: False
    path: /mnt/share/toky/Datasets/LLMC/wikitext2/
    bs: 1
    inference_per_block: False
    num_samples: 50
    # num_eval_tokens: 3
quant:
    method: RTN
    weight:
        bit: 8
        symmetric: True
        granularity: per_channel
        group_size: -1
    act:
        bit: 8
        symmetric: True
        granularity: per_token
    kvcache:
        method: Kivi
        bit: 8
        symmetric: True
        granularity: per_token
save:
    save_fake: False
    save_path: /mnt/share/toky/Projects/LLMC_Test/llmc_quantized/SmolLM-135M-Instruct-rtn_w_a_kivi_quant_kv

